owner: Wicloz
repo: upptime

sites:
  - name: Munin
    url: https://munin.wicloz.rocks/
  - name: SearX
    url: https://searx.wicloz.rocks/
  - name: Nextcloud
    url: https://cloud.wicloz.rocks/
  - name: RoundCube
    url: https://peamail.net/

status-website:
  cname: uptime.wicloz.rocks
  name: Upptime
