owner: Wicloz
repo: upptime

sites:
  - name: Munin
    url: https://munin.wicloz.rocks/
  - name: SearX
    url: https://searx.wicloz.rocks/
  - name: Nextcloud
    url: https://cloud.wicloz.rocks/
  - name: RoundCube
    url: https://peamail.net/
  - name: MTG Saga
    url: https://mtgsaga.wicloz.rocks/
  - name: MusicDL
    url: https://musicdl.wicloz.rocks/
  - name: LMS
    url: https://lms.wicloz.rocks/
  - name: Invoice Ninja
    url: https://invoices.wicloz.rocks/
  - name: Rocket.Chat
    url: https://chat.wicloz.rocks/
  - name: Gitea
    url: https://git.wicloz.rocks/
  - name: Vaultwarden
    url: https://vault.wicloz.rocks/

  - name: Transmission Web
    url: https://torrents.wicloz.rocks/
    expectedStatusCodes:
      - 401
  - name: phpMyAdmin
    url: https://myadmin.wicloz.rocks/
    expectedStatusCodes:
      - 401
  - name: phpPgAdmin
    url: https://pgadmin.wicloz.rocks/
    expectedStatusCodes:
      - 401

  - name: Rimworld Together
    check: "tcp-ping"
    url: rimrim.wicloz.rocks
    port: 25555
    
  - name: SSH
    check: "tcp-ping"
    url: home.wicloz.rocks
    port: 22
  - name: SMTP
    check: "tcp-ping"
    url: peamail.net
    port: 25
  - name: SMTPS
    check: "tcp-ping"
    url: peamail.net
    port: 465
  - name: SubmissionS
    check: "tcp-ping"
    url: peamail.net
    port: 587
  - name: IMAPS
    check: "tcp-ping"
    url: peamail.net
    port: 993

status-website:
  cname: uptime.wicloz.rocks
  name: Upptime
