owner: Wicloz
repo: upptime

sites:
  - name: Munin
    url: https://munin.wicloz.rocks/
  - name: SearX
    url: https://searx.wicloz.rocks/
  - name: Nextcloud
    url: https://cloud.wicloz.rocks/
  - name: RoundCube
    url: https://peamail.net/
  - name: MTG Saga
    url: https://mtgsaga.wicloz.rocks/
  - name: MusicDL
    url: https://musicdl.wicloz.rocks/
  - name: LMS
    url: https://lms.wicloz.rocks/
  - name: Invoice Ninja
    url: https://invoices.wicloz.rocks/
  - name: Rocket.Chat
    url: https://chat.wicloz.rocks/
  - name: Transmission Web
    url: https://torrents.wicloz.rocks/

status-website:
  cname: uptime.wicloz.rocks
  name: Upptime
